[package]
name = "blake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytes = "1.4"
dashmap = "5.4"
tokio = { version = "1.28", features = ["full"] }
